import React from "react"
import { SessionProvider } from "next-auth/react";
import PageLayout from "src/layouts/page-layout";
import "../index.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className="min-h-screen flex flex-col">
          <PageLayout>
            {children}
          </PageLayout>
        </body>
      </html>
    </SessionProvider>
  )
}
