/*
  Warnings:

  - The primary key for the `Collection` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - You are about to alter the column `id` on the `Collection` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - You are about to alter the column `userId` on the `Collection` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - The primary key for the `CollectionEmail` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - You are about to alter the column `id` on the `CollectionEmail` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - You are about to alter the column `collectionId` on the `CollectionEmail` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - You are about to alter the column `emailId` on the `CollectionEmail` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - The primary key for the `Email` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - You are about to alter the column `id` on the `Email` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - You are about to alter the column `senderId` on the `Email` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - You are about to alter the column `screenshotId` on the `Email` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - The primary key for the `EmailScreenshot` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - You are about to alter the column `id` on the `EmailScreenshot` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - You are about to alter the column `emailId` on the `EmailScreenshot` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - The primary key for the `Sender` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - You are about to alter the column `id` on the `Sender` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - The primary key for the `User` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - You are about to alter the column `id` on the `User` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.

*/
-- DropForeignKey
ALTER TABLE "Collection" DROP CONSTRAINT "Collection_userId_fkey";

-- DropForeignKey
ALTER TABLE "CollectionEmail" DROP CONSTRAINT "CollectionEmail_collectionId_fkey";

-- DropForeignKey
ALTER TABLE "CollectionEmail" DROP CONSTRAINT "CollectionEmail_emailId_fkey";

-- DropForeignKey
ALTER TABLE "Email" DROP CONSTRAINT "Email_screenshotId_fkey";

-- DropForeignKey
ALTER TABLE "Email" DROP CONSTRAINT "Email_senderId_fkey";

-- AlterTable
ALTER TABLE "Collection" DROP CONSTRAINT "Collection_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE INTEGER,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ALTER COLUMN "userId" SET DATA TYPE INTEGER,
ADD CONSTRAINT "Collection_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "CollectionEmail" DROP CONSTRAINT "CollectionEmail_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE INTEGER,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ALTER COLUMN "collectionId" SET DATA TYPE INTEGER,
ALTER COLUMN "emailId" SET DATA TYPE INTEGER,
ADD CONSTRAINT "CollectionEmail_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "Email" DROP CONSTRAINT "Email_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE INTEGER,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ALTER COLUMN "senderId" SET DATA TYPE INTEGER,
ALTER COLUMN "screenshotId" SET DATA TYPE INTEGER,
ADD CONSTRAINT "Email_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "EmailScreenshot" DROP CONSTRAINT "EmailScreenshot_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE INTEGER,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ALTER COLUMN "emailId" SET DATA TYPE INTEGER,
ADD CONSTRAINT "EmailScreenshot_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "Sender" DROP CONSTRAINT "Sender_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE INTEGER,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ADD CONSTRAINT "Sender_pkey" PRIMARY KEY ("id");

-- AlterTable
ALTER TABLE "User" DROP CONSTRAINT "User_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE INTEGER,
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY,
ADD CONSTRAINT "User_pkey" PRIMARY KEY ("id");

-- AddForeignKey
ALTER TABLE "Collection" ADD CONSTRAINT "Collection_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CollectionEmail" ADD CONSTRAINT "CollectionEmail_collectionId_fkey" FOREIGN KEY ("collectionId") REFERENCES "Collection"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CollectionEmail" ADD CONSTRAINT "CollectionEmail_emailId_fkey" FOREIGN KEY ("emailId") REFERENCES "Email"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Email" ADD CONSTRAINT "Email_senderId_fkey" FOREIGN KEY ("senderId") REFERENCES "Sender"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EmailScreenshot" ADD CONSTRAINT "EmailScreenshot_emailId_fkey" FOREIGN KEY ("emailId") REFERENCES "Email"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
